import { getCountries, getCountryCallingCode, type CountryCode } from 'libphonenumber-js'

import type { Locale } from '@/i18n/locales'

/**
 * The countries the phone field offers, and the one it opens on (issue #160,
 * `docs/legacy-inventory.md` sections 1.4 and 7.2).
 *
 * The legacy list was a committed `src/countries.ts` of 249 entries, generated by a script that
 * fetched `restcountries.com` and then hand-edited — so it could drift from the library that
 * validated the numbers, and nothing said when. It is derived from that library's own metadata
 * here, which is the decision recorded on the issue: no generated file to keep in sync.
 *
 * The names are the ones the platform already knows in the language being read, so no list of
 * translations is carried either.
 */

/** Where a field opens when nothing is known about the visitor, by the language they are reading. */
const HOME_COUNTRY: Record<Locale, CountryCode> = {
  en: 'AE',
  ru: 'RU',
  uk: 'UA',
}

/** One entry of the dropdown. */
export interface Country {
  /** ISO 3166-1 alpha-2, which is also what the flag and the validation are keyed by. */
  iso: CountryCode
  /** With the `+`, as it is shown and as the field starts. */
  dialCode: string
  /** In the language being read. */
  name: string
}

const displayNames = (locale: Locale) =>
  new Intl.DisplayNames([locale, 'en'], { type: 'region', fallback: 'code' })

/** A country's name in the language being read: `United Arab Emirates`, `ОАЭ`, `ОАЕ`. */
export function countryName(iso: CountryCode, locale: Locale): string {
  return displayNames(locale).of(iso) ?? iso
}

/**
 * Every country with a dial code, in the order the dropdown lists them: by name, in the language
 * being read. The legacy sorted by the English name whatever the page language.
 */
export function countries(locale: Locale): Country[] {
  const names = displayNames(locale)

  return getCountries()
    .map((iso) => ({
      iso,
      dialCode: `+${getCountryCallingCode(iso)}`,
      name: names.of(iso) ?? iso,
    }))
    .sort((one, other) => one.name.localeCompare(other.name, locale))
}

/**
 * The country a field opens on: where the visitor is, when the request says so, and otherwise
 * the home country of the language they are reading.
 *
 * The legacy opened on `COUNTRIES[1]` — Åland Islands, `+35818` — which is the second entry of a
 * list sorted by name, and a dial code its own matcher could never recognise because it is
 * longer than three digits (section 13).
 */
export function defaultCountry(requested: string | null | undefined, locale: Locale): CountryCode {
  const iso = (requested ?? '').trim().toUpperCase()
  const known = getCountries().find((country) => country === iso)

  return known ?? HOME_COUNTRY[locale]
}
