import { defineConfig, globalIgnores } from 'eslint/config'
import nextCoreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'
import betterTailwindcss from 'eslint-plugin-better-tailwindcss'

export default defineConfig([
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      '@typescript-eslint/ban-ts-comment': 'warn',
      '@typescript-eslint/no-empty-object-type': 'warn',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          vars: 'all',
          args: 'after-used',
          ignoreRestSiblings: false,
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          destructuredArrayIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^(_|ignore)',
        },
      ],
    },
  },
  {
    // Tailwind discipline (docs/adr/0006-styling-and-motion.md). Ordering and
    // wrapping belong to prettier-plugin-tailwindcss, so those rules stay off.
    files: ['src/**/*.{ts,tsx}'],
    plugins: { 'better-tailwindcss': betterTailwindcss },
    rules: {
      ...betterTailwindcss.configs['recommended-warn'].rules,
      'better-tailwindcss/enforce-consistent-class-order': 'off',
      'better-tailwindcss/enforce-consistent-line-wrapping': 'off',
      'better-tailwindcss/no-unknown-classes': [
        'error',
        {
          // The parity base layer (docs/adr/0006-styling-and-motion.md) reproduces the
          // legacy global classes as unlayered CSS, which the plugin does not read, so the
          // finite set is listed here. Nothing else may be added: a class that is not a
          // Tailwind utility and not in this list is a typo.
          ignore: [
            '^button$',
            '^card$',
            '^big$',
            '^middle$',
            '^dark$',
            '^darkening$',
            '^hero-darkening$',
            '^option-darkening$',
          ],
        },
      ],
      'better-tailwindcss/no-conflicting-classes': 'error',
      'better-tailwindcss/no-duplicate-classes': 'error',
      // Values belong in @theme, not in class names. Justify exceptions inline.
      'better-tailwindcss/no-restricted-classes': [
        'warn',
        {
          restrict: [
            {
              pattern: '^.*\\[.+\\]$',
              message:
                'Arbitrary value: add a token to @theme in src/app/(frontend)/globals.css instead (docs/adr/0006).',
            },
          ],
        },
      ],
    },
    settings: {
      'better-tailwindcss': {
        entryPoint: 'src/app/(frontend)/globals.css',
      },
    },
  },
  {
    // No locale ternaries in components (issue #163, AGENTS.md section 2, ADR-0003).
    //
    // The legacy site decided what to render by comparing the locale in 77 places across 18
    // files (`docs/i18n-audit.md`), which is why `uk` could never be enabled: every one of them
    // would have fallen through to English. A string belongs in a message catalogue or in a
    // localized Payload field, and neither needs the component to know which language it is.
    //
    // Scoped to the code that renders. `src/i18n` compares locales because that is its job, and
    // so do the collections that enumerate them.
    files: ['src/app/**/*.{ts,tsx}', 'src/components/**/*.{ts,tsx}', 'src/blocks/**/*.{ts,tsx}'],
    rules: {
      'no-restricted-syntax': [
        'error',
        ...['locale', 'lang', 'language'].flatMap((name) =>
          [
            `BinaryExpression[operator=/^[!=]==?$/][left.name='${name}'][right.value=/^(en|ru|uk)$/]`,
            `BinaryExpression[operator=/^[!=]==?$/][left.property.name='${name}'][right.value=/^(en|ru|uk)$/]`,
            `BinaryExpression[operator=/^[!=]==?$/][right.name='${name}'][left.value=/^(en|ru|uk)$/]`,
            `BinaryExpression[operator=/^[!=]==?$/][right.property.name='${name}'][left.value=/^(en|ru|uk)$/]`,
          ].map((selector) => ({
            selector,
            message:
              'No locale ternaries: put the string in the message catalogue or in a localized Payload field (docs/i18n-audit.md, ADR-0003). A hidden locale must be able to render this file.',
          })),
        ),
      ],
    },
  },
  {
    // Migration files are generated by `payload migrate:create`.
    files: ['src/migrations/**/*.ts'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },
  globalIgnores([
    '.next/',
    'coverage/',
    'playwright-report/',
    'test-results/',
    'src/payload-types.ts',
    'src/payload-generated-schema.ts',
    'src/app/(payload)/admin/importMap.js',
    'src/migrations/*.json',
  ]),
])
