#!/usr/bin/env bash
# Self-test of the convention checks with positive and negative fixtures.
# Runs in CI (ci.yml, static job) and locally via `bun run check:conventions`.
set -euo pipefail
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
root="$(cd "$here/../.." && pwd)"
pass=0
fail=0

expect() { # expect <ok|fail> "<description>" -- <command...>
  local want="$1" desc="$2" got
  shift 3
  if "$@" >/dev/null 2>&1; then got=ok; else got=fail; fi
  if [[ "$got" == "$want" ]]; then
    pass=$((pass + 1)); echo "  ok    $desc"
  else
    fail=$((fail + 1)); echo "  FAIL  $desc (expected $want, got $got)"
  fi
}

branch="bash $here/check-branch-name.sh"
echo "check-branch-name.sh"
expect ok   "conventional branch"       -- $branch feat/42-hero-section
expect ok   "fix with multi-word slug"  -- $branch fix/7-sitemap-citizens-typo
expect ok   "master"                    -- $branch master
expect ok   "legacy"                    -- $branch legacy
expect ok   "dependabot branch"         -- $branch dependabot/npm_and_yarn/next-16.3.6
expect fail "agent prefix claude/"      -- $branch claude/distracted-tharp-9849c2
expect fail "agent prefix codex/"       -- $branch codex/fix-thing
expect fail "agent prefix copilot/"     -- $branch copilot/fix-thing
expect fail "placeholder prefix"        -- $branch use_convention_prefix_and_not_this/x
expect fail "missing issue number"      -- $branch feat/hero-section
expect fail "uppercase"                 -- $branch Feat/42-Hero
expect fail "unknown type"              -- $branch feature/42-hero
expect fail "underscore in slug"        -- $branch feat/42-hero_section
expect ok   "deny-only accepts other names" -- $branch --deny-only test-branch
expect fail "deny-only rejects claude/"     -- $branch --deny-only claude/x

echo "scan-attribution.sh"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
g() { git -C "$tmp" -c user.name=Owner -c user.email=owner@example.com "$@"; }
g init -q -b main
g commit -q --allow-empty -m "chore: base"
base="$(g rev-parse HEAD)"
g commit -q --allow-empty -m "feat: clean commit"
scan() { # scan "<env assignments and args>" runs the scanner inside the fixture repo
  bash -c "cd '$tmp' && $1 bash '$here/scan-attribution.sh' $2"
}
expect ok   "clean commit range"                 -- scan "" "$base..HEAD"
expect ok   "clean PR title and body"            -- scan "PR_TITLE='feat: hero' PR_BODY='Closes #1'" ""
expect fail "PR body with generated-with footer" -- scan "PR_BODY='🤖 Generated with [Claude Code](https://claude.com/claude-code)'" ""
expect fail "PR body with made-by claude"        -- scan "PR_BODY='made by Claude'" ""
expect fail "PR body with generated-by footer and link" -- scan "PR_BODY='_Generated by [Claude Code](https://claude.ai/code/session_01ABC)_'" ""
expect fail "PR body with a tool session link only"     -- scan "PR_BODY='Session: https://claude.ai/code/session_01ABC'" ""
expect fail "PR body with made-with-ai"                 -- scan "PR_BODY='Made with AI assistance'" ""
expect ok   "prose mention of a tool is allowed"        -- scan "PR_BODY='The Claude Code hook blocks attribution; types generated by payload'" ""
g commit -q --allow-empty -m "$(printf 'feat: with trailer\n\nCo-Authored-By: Claude <noreply@anthropic.com>')"
expect fail "co-authored-by claude trailer"      -- scan "" "$base..HEAD"
git -C "$tmp" -c user.name=Bot -c user.email=bot@anthropic.com commit -q --allow-empty -m "feat: bot authored"
expect fail "anthropic author email"             -- scan "" "$base..HEAD"
git -C "$tmp" checkout -q -b identity "$base"
git -C "$tmp" -c user.name=Claude -c user.email=claude@example.com commit -q --allow-empty -m "feat: agent named as author"
expect fail "agent name as author"               -- scan "" "$base..identity"
expect ok   "dependabot body skipped"            -- scan "SKIP_BODY=1 PR_TITLE='build: bump x' PR_BODY='Co-authored-by: dependabot[bot]'" ""

echo "scrub-attribution.sh"
strip() { printf '%s' "$1" | bash "$here/scrub-attribution.sh" --strip; }
stripped() { [[ "$(strip "$1")" == "$2" ]]; }
expect ok   "generated-by footer under a rule is removed"  -- stripped "$(printf 'Body\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_x)_\n')" "Body"
expect ok   "generated-with footer and link are removed"   -- stripped "$(printf 'Body\n\n🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\nhttps://claude.ai/code/session_x\n')" "Body"
expect ok   "co-authored-by trailer is removed"            -- stripped "$(printf 'Body\n\nCo-Authored-By: Claude <noreply@anthropic.com>\n')" "Body"
expect ok   "rule with real content stays"                 -- stripped "$(printf 'Body\n\n---\nFooter kept\n')" "$(printf 'Body\n\n---\nFooter kept')"
expect ok   "prose stays"                                  -- stripped "$(printf 'Types generated by payload.\nThe Claude Code hook.\n')" "$(printf 'Types generated by payload.\nThe Claude Code hook.')"

echo "sanitize-commit-msg.sh"
sanitized() { local f; f="$(mktemp)"; printf '%s\n' "$1" > "$f"; bash "$here/sanitize-commit-msg.sh" "$f" 2>/dev/null; [[ "$(cat "$f")" == "$2" ]]; }
expect ok   "co-author trailer dropped"          -- sanitized "$(printf 'feat: x\n\nCo-Authored-By: Claude <noreply@anthropic.com>')" "feat: x"
expect ok   "session trailer dropped"            -- sanitized "$(printf 'feat: x\n\nClaude-Session: https://claude.ai/code/session_x')" "feat: x"
expect ok   "human sign-off kept"                -- sanitized "$(printf 'feat: x\n\nSigned-off-by: Owner <owner@example.com>')" "$(printf 'feat: x\n\nSigned-off-by: Owner <owner@example.com>')"
expect ok   "body prose kept"                    -- sanitized "$(printf 'docs: x\n\nTypes generated by payload are committed.')" "$(printf 'docs: x\n\nTypes generated by payload are committed.')"

echo "commitlint"
lint() { bash -c "cd '$root' && printf '%s' \"\$1\" | bunx commitlint" lint "$1"; }
expect ok   "conventional header"                -- lint 'feat: add hero section'
expect fail "no type"                            -- lint 'Add hero section'
expect fail "co-authored-by claude trailer"      -- lint "$(printf 'feat: add x\n\nCo-Authored-By: Claude <noreply@anthropic.com>')"
expect fail "generated-with footer"              -- lint "$(printf 'feat: add x\n\nGenerated with Claude Code')"
expect fail "claude-session trailer"             -- lint "$(printf 'feat: add x\n\nClaude-Session: https://claude.ai/code/session_x')"
expect fail "generated-by footer with a tool link"    -- lint "$(printf 'feat: add x\n\n---\n_Generated by [Claude Code](https://claude.ai/code/session_x)_')"
expect ok   "prose mention of a tool"                 -- lint "$(printf 'docs: describe the claude code hook\n\nTypes generated by payload are committed.')"

echo "check-visual-budget.sh / visual-update.sh"
vb="$(mktemp -d)"; head -c 2048 /dev/zero > "$vb/a.png"
expect ok   "budget under the limit"            -- env VISUAL_BUDGET_BYTES=4096 bash "$here/check-visual-budget.sh" "$vb"
expect fail "budget over the limit"             -- env VISUAL_BUDGET_BYTES=1024 bash "$here/check-visual-budget.sh" "$vb"
expect ok   "missing baseline directory"        -- bash "$here/check-visual-budget.sh" "$vb/none"
expect ok   "visual update allowed on linux"    -- env VISUAL_UPDATE_OS=Linux VISUAL_UPDATE_DRY_RUN=1 bash "$here/visual-update.sh"
expect fail "visual update refused elsewhere"   -- env VISUAL_UPDATE_OS=Darwin bash "$here/visual-update.sh"

echo "check-tests-required.sh"
tr="$(mktemp -d)"
t() { git -C "$tr" -c user.name=Owner -c user.email=owner@example.com "$@"; }
tests_required() { bash -c "cd '$tr' && $1 bash '$here/check-tests-required.sh' $2"; }
t init -q -b main
t commit -q --allow-empty -m "chore: base"
tbase="$(t rev-parse HEAD)"
mkdir -p "$tr/src/lib" "$tr/src/migrations" "$tr/tests/unit"
echo 'export const a = 1' > "$tr/src/lib/a.ts" && t add -A && t commit -q -m "feat: code only"
expect fail "code without tests"                -- tests_required "PR_LABELS=''" "$tbase..HEAD"
expect ok   "code without tests but waived"     -- tests_required "PR_LABELS='type:feature,no-tests-needed'" "$tbase..HEAD"
echo 'it' > "$tr/tests/unit/a.test.ts" && t add -A && t commit -q -m "test: add a test"
expect ok   "code with tests"                   -- tests_required "PR_LABELS=''" "$tbase..HEAD"
mbase="$(t rev-parse HEAD)"
echo 'migration' > "$tr/src/migrations/1.ts" && t add -A && t commit -q -m "chore: migration only"
expect ok   "migration only"                    -- tests_required "PR_LABELS=''" "$mbase..HEAD"
expect ok   "nothing changed"                   -- tests_required "PR_LABELS=''" "HEAD..HEAD"

echo "block-attribution.sh"
hook() { printf '%s' "$1" | bash "$root/.claude/hooks/block-attribution.sh"; }
expect ok   "plain commit"                       -- hook '{"tool_input":{"command":"git commit -m \"feat: add x\""}}'
expect fail "commit with generated-by footer"    -- hook '{"tool_input":{"command":"git commit -m \"feat: x\" -m \"Generated by [Claude Code](https://claude.ai/code/session_x)\""}}'
expect fail "commit with co-authored-by claude"  -- hook '{"tool_input":{"command":"git commit -m \"feat: x\" -m \"Co-Authored-By: Claude <noreply@anthropic.com>\""}}'
expect fail "pr body with generated-with footer" -- hook '{"tool_input":{"command":"gh pr create --title x --body \"Generated with Claude Code\""}}'
expect fail "force push"                         -- hook '{"tool_input":{"command":"git push --force origin feat/1-x"}}'
expect fail "push to master"                     -- hook '{"tool_input":{"command":"git push origin master"}}'
expect ok   "push to a feature branch"           -- hook '{"tool_input":{"command":"git push -u origin feat/1-x"}}'
expect fail "vendor address as git author"       -- hook '{"tool_input":{"command":"git config user.email noreply@anthropic.com"}}'

echo
echo "passed: $pass  failed: $fail"
[[ $fail -eq 0 ]]
