/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    airports: Airport;
    aircraft: Aircraft;
    contacts: Contact;
    yachts: Yacht;
    'empty-legs': EmptyLeg;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    airports: AirportsSelect<false> | AirportsSelect<true>;
    aircraft: AircraftSelect<false> | AircraftSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    yachts: YachtsSelect<false> | YachtsSelect<true>;
    'empty-legs': EmptyLegsSelect<false> | EmptyLegsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ru' | 'uk') | ('en' | 'ru' | 'uk')[];
  globals: {};
  globalsSelect: {};
  locale: 'en' | 'ru' | 'uk';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Editors run the content. Admins also run the people and the settings.
   */
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * What the image shows, in this locale. Read out by screen readers.
   */
  alt: string;
  /**
   * Set while the file still lives on a legacy host. Components prefer it over the upload.
   */
  externalUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    gallery?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Shown in the admin and used as the default SEO title.
   */
  title: string;
  /**
   * The path after the locale, without a leading slash. Empty means the home page. Not localized: the legacy URLs are identical in every language and parity depends on that.
   */
  slug?: string | null;
  /**
   * The sections of this page, in the order they are rendered.
   */
  layout?: unknown[] | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports".
 */
export interface Airport {
  id: number;
  /**
   * Four-letter ICAO code, upper-cased. The empty legs block looks airports up by it.
   */
  icao?: string | null;
  /**
   * Three-letter IATA code, upper-cased.
   */
  iata?: string | null;
  /**
   * The airport name as a traveller would read it in this language.
   */
  name?: string | null;
  city?: string | null;
  country?: string | null;
  /**
   * Other names the search should match, comma separated. The legacy column is the misspelled `alies_en` / `alies_ru`.
   */
  aliases?: string | null;
  /**
   * Airport type as the source data describes it. Never rendered today.
   */
  type?: string | null;
  /**
   * Annual passengers, used to rank search results. A number here, unlike the legacy text column; the import parses that text with parsePassengersPerYear before writing.
   */
  passengersPerYear?: number | null;
  /**
   * ISO country code, upper-cased.
   */
  isoCode?: string | null;
  /**
   * Offset as the legacy data records it, kept verbatim rather than parsed.
   */
  gmtOffset?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  /**
   * Wikidata identifier from the legacy `new_airports` table.
   */
  wikidata?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft".
 */
export interface Aircraft {
  id: number;
  /**
   * The registration as it is painted on the aircraft, hyphens included.
   */
  registrationDisplay: string;
  /**
   * Canonical registration, derived from the one above by upper-casing and removing hyphens. The natural key the import merges on.
   */
  registration?: string | null;
  /**
   * The legacy slug, kept so /aircraft/<slug> does not move.
   */
  slug?: string | null;
  availability?: ('available' | 'unavailable') | null;
  /**
   * From the legacy is_for_charter, is_for_sale, is_for_lease and is_cargo.
   */
  offerings?: ('charter' | 'sale' | 'lease' | 'cargo')[] | null;
  /**
   * The aircraft type, as the legacy aircraft_type_* columns describe it.
   */
  type?: {
    name?: string | null;
    slug?: string | null;
    category?: string | null;
    manufacturer?: string | null;
    model?: string | null;
  };
  specification?: {
    passengers?: number | null;
    typePassengers?: number | null;
    rangeMaximum?: number | null;
    speedTypical?: number | null;
    cabinHeight?: number | null;
    cabinLength?: number | null;
    cabinWidth?: number | null;
    yearOfProduction?: number | null;
    serialNumber?: string | null;
    hoursFlown?: number | null;
    cycles?: number | null;
    interiorRefit?: string | null;
    exteriorRefit?: string | null;
    luggageVolume?: string | null;
    sleepingPlaces?: number | null;
    divanSeats?: number | null;
    beds?: number | null;
  };
  /**
   * The legacy extension_* booleans. Stored but not rendered today.
   */
  amenities?: {
    cabinCrew?: boolean | null;
    lavatory?: boolean | null;
    shower?: boolean | null;
    hotMeal?: boolean | null;
    wirelessInternet?: boolean | null;
    satellitePhone?: boolean | null;
    petsAllowed?: boolean | null;
    refurbishment?: boolean | null;
  };
  operator?: {
    companyName?: string | null;
    companySlug?: string | null;
    technicalOperator?: string | null;
  };
  /**
   * Resolved from the legacy airport_icao during the import of E5.6.
   */
  baseAirport?: (number | null) | Airport;
  /**
   * From the legacy extension_description. Localized, unlike the source column, which held one language.
   */
  description?: string | null;
  specialEquipment?: string | null;
  /**
   * The legacy extension_view_360 iframe source, when there is one.
   */
  view360Url?: string | null;
  brochure?: {
    url?: string | null;
    name?: string | null;
  };
  /**
   * In the order they are shown. The first is the hero; the rich detail layout needs more than one.
   */
  images?:
    | {
        type: 'exterior' | 'cabin' | 'cockpit';
        media?: (number | null) | Media;
        /**
         * Set while the file still lives on a legacy host, as on Media.
         */
        externalUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Every legacy column with no field of its own, kept verbatim so nothing is lost before E5.13 reconciles.
   */
  legacyAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Where this document came from (ADR-0002 section 8).
   */
  provenance: {
    origin: 'aircrafts-catalog' | 'vehicles-legacy' | 'manual';
    legacyAircraftId?: number | null;
    legacyVehicleId?: number | null;
    legacyTailNumber?: string | null;
    legacySlug?: string | null;
    /**
     * Every legacy row folded into this document.
     */
    mergedFrom?:
      | {
          table: string;
          id: number;
        }[]
      | null;
    importRunId?: string | null;
    importedAt?: string | null;
    verifiedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Personal data. Administrators only, and never rendered on the public site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: number;
  /**
   * From the legacy contact.name.
   */
  name: string;
  /**
   * What this person does, in their own words: captain, broker, owner. No legacy column, so the import leaves it empty.
   */
  role?: string | null;
  /**
   * From the legacy contact.phone. Personal data.
   */
  phone?: string | null;
  /**
   * From the legacy contact.email. Personal data.
   */
  email?: string | null;
  /**
   * No legacy column, so the import leaves it empty. Media is public: do not upload anything here that the person would not want served from a URL.
   */
  photo?: (number | null) | Media;
  /**
   * Where this document came from (ADR-0002 section 8).
   */
  provenance: {
    origin: 'contact-legacy' | 'manual';
    legacyContactId?: number | null;
    importRunId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yachts".
 */
export interface Yacht {
  id: number;
  /**
   * The name both legacy cards render, without the manufacturer.
   */
  name: string;
  /**
   * Which legacy catalogue this listing belongs to: charter (new_yachts) or sale (yachts).
   */
  listingType: 'charter' | 'sale';
  /**
   * The URL of the detail page. Generated from the name when a listing is created, then left alone: changing it moves a published URL. A name in a script this cannot transliterate leaves it empty, and you are asked for one.
   */
  slug?: string | null;
  /**
   * Where the yacht is, as both legacy tables record it.
   */
  location?: string | null;
  /**
   * Length in feet, as the legacy numeric column holds it. The card renders the metres itself.
   */
  length?: number | null;
  /**
   * From the legacy description and description_ru, which were two columns rather than a locale.
   */
  description?: string | null;
  /**
   * In the order they are shown; the first is the card cover. From the legacy photos and pictures arrays, whose order was the order of the array.
   */
  photos?:
    | {
        media?: (number | null) | Media;
        /**
         * Set while the file still lives on the legacy bucket, as on Media.
         */
        externalUrl?: string | null;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The columns of the legacy new_yachts table.
   */
  charter?: {
    manufacturer?: string | null;
    owner?: string | null;
    /**
     * Per hour, as the legacy card renders it.
     */
    customerPrice?: number | null;
    /**
     * The legacy bussines_price, misspelled in the source and never rendered. Kept so nothing is lost.
     */
    businessPrice?: number | null;
    /**
     * The legacy column is free text; the import maps it to one of these.
     */
    currency?: ('AED' | 'USD' | 'EUR') | null;
    minHours?: number | null;
    guestsDay?: number | null;
    guestsNight?: number | null;
    /**
     * Text, not a number: the legacy column is text and the card prints it verbatim.
     */
    cabins?: string | null;
    bathrooms?: string | null;
    refit?: number | null;
    /**
     * From the legacy included and included_en.
     */
    included?: string | null;
  };
  /**
   * The columns of the legacy yachts table.
   */
  sale?: {
    /**
     * The builder.
     */
    shipyard?: string | null;
    year?: number | null;
    /**
     * No legacy column: the sale table held no price and the card showed none. Left empty by the import.
     */
    price?: number | null;
    currency?: ('AED' | 'USD' | 'EUR') | null;
    beam?: number | null;
    draft?: number | null;
    /**
     * An integer here, unlike the charter side.
     */
    cabins?: number | null;
    guests?: number | null;
    crew?: number | null;
    cruisingSpeed?: number | null;
    maxSpeed?: number | null;
  };
  /**
   * From the legacy new_yachts.contact_id. Personal data: administrators only, and never part of a public response.
   */
  contact?: (number | null) | Contact;
  /**
   * From the legacy new_yachts.captain_id. Personal data: administrators only, and never part of a public response.
   */
  captain?: (number | null) | Contact;
  /**
   * Every legacy column with no field of its own, kept verbatim so nothing is lost before E5.13 reconciles.
   */
  legacyAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Where this document came from (ADR-0002 section 8).
   */
  provenance: {
    origin: 'new-yachts-charter' | 'yachts-sale' | 'manual';
    legacyId?: number | null;
    legacySlug?: string | null;
    importRunId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empty-legs".
 */
export interface EmptyLeg {
  id: number;
  /**
   * Filled in by the admin list from the two codes below; it is what the row is called in a list of rows.
   */
  route?: string | null;
  /**
   * Resolved from the legacy `from` code during the import of E5.11.
   */
  departureAirport?: (number | null) | Airport;
  /**
   * The four-letter code as the leg was entered. Kept even when the airport above is set, and the only record of the route when no airport matches: the legacy section dropped such a row from the page entirely.
   */
  departureIcao?: string | null;
  /**
   * Resolved from the legacy `to` code during the import of E5.11.
   */
  arrivalAirport?: (number | null) | Airport;
  /**
   * The four-letter code as the leg was entered.
   */
  arrivalIcao?: string | null;
  /**
   * Stored in UTC, as the legacy timestamptz was. The card prints the UTC day in en-US, whatever the page language, which is what the legacy card did.
   */
  departureAt: string;
  /**
   * The legacy `end` column. Written by the legacy admin and never rendered.
   */
  arrivalAt?: string | null;
  /**
   * The legacy price column, an integer that defaulted to 0.
   */
  price?: number | null;
  /**
   * No legacy column: the card hard-coded a dollar sign. USD reproduces it.
   */
  currency?: ('USD' | 'EUR' | 'AED') | null;
  /**
   * No legacy column, and the legacy card showed no seat count. Left empty by the import.
   */
  seats?: number | null;
  /**
   * Lowest first. The legacy admin wrote this column and the site ignored it, so rows came back in whatever order the database felt like. A leg with no number sorts last.
   */
  order?: number | null;
  /**
   * The legacy columns were free text the admin typed. The relationship is preferred; the text survives for a leg whose aircraft is not in the catalogue.
   */
  aircraft?: {
    /**
     * Resolved from the legacy type and company during E5.11.
     */
    document?: (number | null) | Aircraft;
    /**
     * The legacy type column.
     */
    type?: string | null;
    /**
     * The legacy category column.
     */
    category?: string | null;
    /**
     * The legacy company column.
     */
    company?: string | null;
    /**
     * The legacy safety column.
     */
    safety?: string | null;
  };
  /**
   * Every legacy column with no field of its own, kept verbatim so nothing is lost before E5.13 reconciles.
   */
  legacyAttributes?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Where this document came from (ADR-0002 section 8).
   */
  provenance: {
    origin: 'empty-legs-legacy' | 'manual';
    legacyId?: number | null;
    importRunId?: string | null;
    importedAt?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'airports';
        value: number | Airport;
      } | null)
    | ({
        relationTo: 'aircraft';
        value: number | Aircraft;
      } | null)
    | ({
        relationTo: 'contacts';
        value: number | Contact;
      } | null)
    | ({
        relationTo: 'yachts';
        value: number | Yacht;
      } | null)
    | ({
        relationTo: 'empty-legs';
        value: number | EmptyLeg;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  externalUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        gallery?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?: T | {};
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "airports_select".
 */
export interface AirportsSelect<T extends boolean = true> {
  icao?: T;
  iata?: T;
  name?: T;
  city?: T;
  country?: T;
  aliases?: T;
  type?: T;
  passengersPerYear?: T;
  isoCode?: T;
  gmtOffset?: T;
  latitude?: T;
  longitude?: T;
  wikidata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "aircraft_select".
 */
export interface AircraftSelect<T extends boolean = true> {
  registrationDisplay?: T;
  registration?: T;
  slug?: T;
  availability?: T;
  offerings?: T;
  type?:
    | T
    | {
        name?: T;
        slug?: T;
        category?: T;
        manufacturer?: T;
        model?: T;
      };
  specification?:
    | T
    | {
        passengers?: T;
        typePassengers?: T;
        rangeMaximum?: T;
        speedTypical?: T;
        cabinHeight?: T;
        cabinLength?: T;
        cabinWidth?: T;
        yearOfProduction?: T;
        serialNumber?: T;
        hoursFlown?: T;
        cycles?: T;
        interiorRefit?: T;
        exteriorRefit?: T;
        luggageVolume?: T;
        sleepingPlaces?: T;
        divanSeats?: T;
        beds?: T;
      };
  amenities?:
    | T
    | {
        cabinCrew?: T;
        lavatory?: T;
        shower?: T;
        hotMeal?: T;
        wirelessInternet?: T;
        satellitePhone?: T;
        petsAllowed?: T;
        refurbishment?: T;
      };
  operator?:
    | T
    | {
        companyName?: T;
        companySlug?: T;
        technicalOperator?: T;
      };
  baseAirport?: T;
  description?: T;
  specialEquipment?: T;
  view360Url?: T;
  brochure?:
    | T
    | {
        url?: T;
        name?: T;
      };
  images?:
    | T
    | {
        type?: T;
        media?: T;
        externalUrl?: T;
        id?: T;
      };
  legacyAttributes?: T;
  provenance?:
    | T
    | {
        origin?: T;
        legacyAircraftId?: T;
        legacyVehicleId?: T;
        legacyTailNumber?: T;
        legacySlug?: T;
        mergedFrom?:
          | T
          | {
              table?: T;
              id?: T;
            };
        importRunId?: T;
        importedAt?: T;
        verifiedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  phone?: T;
  email?: T;
  photo?: T;
  provenance?:
    | T
    | {
        origin?: T;
        legacyContactId?: T;
        importRunId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "yachts_select".
 */
export interface YachtsSelect<T extends boolean = true> {
  name?: T;
  listingType?: T;
  slug?: T;
  location?: T;
  length?: T;
  description?: T;
  photos?:
    | T
    | {
        media?: T;
        externalUrl?: T;
        alt?: T;
        id?: T;
      };
  charter?:
    | T
    | {
        manufacturer?: T;
        owner?: T;
        customerPrice?: T;
        businessPrice?: T;
        currency?: T;
        minHours?: T;
        guestsDay?: T;
        guestsNight?: T;
        cabins?: T;
        bathrooms?: T;
        refit?: T;
        included?: T;
      };
  sale?:
    | T
    | {
        shipyard?: T;
        year?: T;
        price?: T;
        currency?: T;
        beam?: T;
        draft?: T;
        cabins?: T;
        guests?: T;
        crew?: T;
        cruisingSpeed?: T;
        maxSpeed?: T;
      };
  contact?: T;
  captain?: T;
  legacyAttributes?: T;
  provenance?:
    | T
    | {
        origin?: T;
        legacyId?: T;
        legacySlug?: T;
        importRunId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "empty-legs_select".
 */
export interface EmptyLegsSelect<T extends boolean = true> {
  route?: T;
  departureAirport?: T;
  departureIcao?: T;
  arrivalAirport?: T;
  arrivalIcao?: T;
  departureAt?: T;
  arrivalAt?: T;
  price?: T;
  currency?: T;
  seats?: T;
  order?: T;
  aircraft?:
    | T
    | {
        document?: T;
        type?: T;
        category?: T;
        company?: T;
        safety?: T;
      };
  legacyAttributes?: T;
  provenance?:
    | T
    | {
        origin?: T;
        legacyId?: T;
        importRunId?: T;
        importedAt?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}